# This workflow syncs from Withings to Garmin.
# To sync from Garmin to Strava there is
# https://www.weemple.com/weightnet/members
#

on:
  schedule:
    # - cron:  '0 10 * * *'
    # This runs at 10:00 AM UTC each day.
    # * is a special character in YAML so you have to quote this string
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a source tarball
        run: >-
          python -m
          build
          --sdist
          --outdir dist/ .

      - name: Install withings-sync
        run: cd dist && pip install withings-sync-4.2.4.tar.gz

      - name: Execute withings-sync
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          USERID: ${{ secrets.USERID }}
          GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        run: withings-sync -f $(date +"%Y-%m-%d") -v

      - name: Store updated refresh token
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'REFRESH_TOKEN'
          value: "$REFRESH_TOKEN"
          repository: LukeLaz/withings-sync
          token: ${{ secrets.GITHUB_TOKEN }}
    
