on:
  schedule:
    - cron:  '0 10 * * *'
    # This runs at 10:00 AM UTC each day.
    # * is a special character in YAML so you have to quote this string
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a source tarball
        run: >-
          python -m
          build
          --sdist
          --outdir dist/ .

      - name: Install withings-sync
        run: cd dist && pip install withings-sync-4.2.4.tar.gz

      - name: Execute withings-sync
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          USERID: ${{ secrets.USERID }}
        run: withings-sync -f 2024-03-01 -v --to-json
    
