on:
  schedule:
    - cron:  '0 10 * * *'
    # This runs at 10:00 AM UTC each day.
    # * is a special character in YAML so you have to quote this string
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a source tarball
        run: >-
          python -m
          build
          --sdist
          --outdir dist/ .

      - name: ls 
        run: cd dist && ls -il    

      # - name: execute py script # run main.py
        # run: cd withings_sync && python -m sync.py -f 2024-04-01 -v
    
